services:
  api:
    image: node:latest
    container_name: api
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

